parameters:
- name: Environment
  type: string
- name: ResourceGroupName
  type: string
- name: ServiceConnectionName
  type: string
- name: SubscriptionId
  type: string

jobs:
- job: deploy_resources
  steps:
  - download: current
    artifact: function-package
  - download: current
    artifact: bicep-package

  - task: AzureFunctionApp@2
    displayName: Deploy Function App
    inputs:
      azureSubscription: '${{ parameters.ServiceConnectionName }}'
      appType: 'functionAppLinux'
      appName: $(Deployment.AppServiceName.value)
      resourceGroupName: '${{ parameters.ResourceGroupName }}'
      package: '$(Pipeline.Workspace)/function-package/$(Build.BuildNumber).zip'