trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  displayName: Build the application

  jobs:
  - job: build
    displayName: Build
    steps:
      - task: UseDotNet@2
        inputs:
          version: 8.x
      - task: DotNetCoreCLI@2
        displayName: Build Function App
        inputs:
          command: 'build'
          projects: |
            $(System.DefaultWorkingDirectory)/Demo.FunctionApp/Demo.FunctionApp.csproj
          arguments: --output $(System.DefaultWorkingDirectory)/function-package --configuration Release
      - task: DotNetCoreCLI@2
        displayName: Test Function App
        inputs:
          command: 'test'
          projects: |
            $(System.DefaultWorkingDirectory)/Demo.FunctionApp.Test/Demo.FunctionApp.Test.csproj

      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/function-package'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip
          replaceExistingArchive: true

      - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip
        artifact: function-package


- stage: deployment_test
  displayName: Deployment to test
  jobs:
  - template: deployment.yaml
    parameters:
      Environment: 'test'
      ResourceGroupName: 'Test'
      ServiceConnectionName: 'AzureServiceConnection'
      SubscriptionId: '1f6e85e9-1b4e-4360-9dcb-b325427367aa'

- stage: deployment_prod
  displayName: Deployment to test
  jobs:
  - template: deployment.yaml
    parameters:
      Environment: 'prod'
      ResourceGroupName: 'Production'
      ServiceConnectionName: 'AzureServiceConnection'
      SubscriptionId: '1f6e85e9-1b4e-4360-9dcb-b325427367aa'