trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  displayName: Build the application

  jobs:
  - job: build
    displayName: Build
    steps:
      - task: UseDotNet@2
        inputs:
          version: 8.x
      - task: DotNetCoreCLI@2
        displayName: Build Function App
        inputs:
          command: 'build'
          projects: |
            $(System.DefaultWorkingDirectory)/Demo.FunctionApp/Demo.FunctionApp.csproj
          arguments: --output $(System.DefaultWorkingDirectory)/function-package --configuration Release
      - task: DotNetCoreCLI@2
        displayName: Test Function App
        inputs:
          command: 'test'
          projects: |
            $(System.DefaultWorkingDirectory)/Demo.FunctionApp.Test/Demo.FunctionApp.Test.csproj

      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/function-package'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip
          replaceExistingArchive: true

      - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip
        artifact: function-package
- stage: test
  displayName: Deploy to test
  jobs:
  - job: deploy_resources
    steps:
    - download: current
      artifact: function-package

    - task: AzureFunctionApp@2
      displayName: Deploy Function App
      inputs:
        azureSubscription: 'AzureServiceConnection'
        appType: 'functionAppLinux'
        appName: 'hb-demo-functionscicd-test'
        resourceGroupName: 'Test'
        package: '$(Pipeline.Workspace)/function-package/$(Build.BuildNumber).zip'